### ISSUE TITLE
Add support for Abosom.org

### ISSUE THREAD

**Issue by ZenyattaAbosom** [electrum-altcoin/electrum#27]
Further to our discussion in [discord.abosom.org](discord.abosom.org), we would be delighted to have our coin added to the list of supported projects for these forks of Electrum moving forward.

Abosom is a Dash codebase fork which includes DIP003 and Proof of stake. Our full [codebase can be found here](code.abosom.org)

We are looking forward to working with you guys in the future.

Danke

Zenyatta

**Comment by ZenyattaAbosom** [comment]
@ahmedbodi do you think It would be useful to add our scope of work document here?

It may inform other projects of what is required for electrum, why its needed and the sort of timescale for implementation.

What are your thoughts?

**Comment by ZenyattaAbosom** [comment]
This has been done and we are testing with the most recent release.

**Comment by ahmedbodi** [comment]
Closed by #32
