### ISSUE TITLE
How to fix android build ?

### ISSUE THREAD

**Issue by mraksoll4** [electrum-altcoin/electrum#40]
No mater what network i select is always 

```
03-31 04:58:37.941 27721 27749 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/main.py", line 334, in <module>
03-31 04:58:37.941 27721 27749 I python  :   File "/home/user/wspace/electrum/.buildozer/android/app/electrum/constants.py", line 54, in select_network
```

If compile standart , no errors and all work

**Comment by ahmedbodi** [comment]
the docs havent been updated for the new build process. you must select a network with the --network parameter

**Comment by litecoinfinance** [comment]
i select it ) Problem andro build ignore it ( android not accept params )
